### ISSUE TITLE
About travel time estimation

### ISSUE THREAD

**Issue by wwy12345** [aptx1231/START#1]

**Comment by aptx1231** [comment]
When performing the ETA task, I only input the "segment sequence" and "start time", and there is no time corresponding to the segment. This is mentioned in the paper, and the same is true in the code.
Do you think this is also unfair？

**Comment by wwy12345** [comment]
After checking your codes, I am sure there is something wrong in my understanding. I would retract my words and sincerely apologize.  I recommend that the author describe the steps to set the time interval to 0 in the paper.

**Comment by aptx1231** [comment]
Thank you very much for your suggestion. There is no detailed description in this article. Thank you!
