### ISSUE TITLE
About Temporal Shifting Strategy Implementation

### ISSUE THREAD

**Issue by mamazi0131** [aptx1231/START#2]
I have been studying your work and I am particularly interested in the code implementation of the augmentation strategies mentioned in the paper.

While exploring the publicly available code, I noticed that the specific code for the mentioned augmentation strategies is not publicly accessible. However, through reverse engineering on the publicly available data, I discovered that the paper states the selection of subsequences for the shift operation with a probability of 0.15. During the reverse engineering process, we found that there are multiple subsequences for the shift operation on a single road (inferred from the tau g of the shift). We are interested in obtaining a more detailed understanding of this aspect of the implementation.

If possible, could you kindly provide us with the detailed settings and, if available, the code related to these augmentation strategies? We would greatly appreciate any assistance you can provide in this regard.

**Comment by aptx1231** [comment]
这里的做法是，对于一个n个road组成的轨迹，选择15%的路段对【通行时间】做扰动，扰动的方法是根据历史通行时间和当前通行时间，并乘上一个0.15-0.30之间的比例。

论文中说的是：randomly select a subset of roads (scale r2 = 0.15)。不是the selection of subsequences，随机选的是road，不是subsequences。

具体来说，代码实现的时候，起点出发时间不变，首先用t(i+1)-t(i)计算每一条路的通行时间，并根据历史信息统计历史的通行时间。

然后选择15%的路，对通行时间进行如公式中的扰动，得到扰动之后的通行时间。

最后，起点的出发时间不变，根据通行时间一步一步的累加，得到每一条路的出发时间，也就是新的时间戳了。

值得注意的是，虽然只扰动了15%的路的【通行时间】，但是数据中反应出的【出发时间】会变化很多，简单的例子我扰动第2条路的通行时间，假设多了1min，那么后边所有的道路的出发时间都会晚1min。

你提到的这句话：multiple subsequences for the shift operation on a single road (inferred from the t_aug of the shift)

我不太明白是啥意思，你可以用中文解释一下吗？
